all:
	curl --remote-name-all https://lindat.mff.cuni.cz/repository/xmlui/bitstream/handle/11234/1-3131/udpipe-ud-2.5-191206.zip
	unzip udpipe-ud-2.5-191206.zip
	mv udpipe-ud-2.5-191206/* models/
	rm -f udpipe-ud-2.5-191206.zip
